name: Sawnsco
favicon: null
layout_spectrum: 0.908026568358764
typography_spectrum: 0.7719538358505815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 52.32.215.222
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.36656450130976737
  lightness: 0.3232569352257997
  saturation: 0.1574995769187808
  rhythmicContrast: 0.5608365456573665
purpose: []
