layout_spectrum: 0.7538799243278359
typography_spectrum: 0.4561774962526368
color:
  brandColors:
    - '#000000'
    - '#027fb3'
    - '#959595'
    - '#666666'
    - '#043950'
  brandStrength: 0.3520926783972484
  lightness: 0.7014854286114989
  saturation: 0.1330145385316435
  rhythmicContrast: 0.39526493469179413
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-76571740-1
  facebook: null
  twitter: null
name: Sawnsco
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'About Us '
    id: 5ec43b36-c781-4c3d-bb12-2bbd861f5306
    type: content
  - name: Our Ventures
    id: 550aa410-5b98-4acf-82c2-924a8bd5b093
    type: content
  - name: Betl Solutions
    url: >-
      https://app.thegrid.io/app/site/live?siteID=20532492-8d47-4d5f-bf78-25b121080dc5
    type: external
  - name: AVN Tobacco
    url: >-
      https://app.thegrid.io/app/site/nav?siteID=456c11df-4ab2-4c1a-a013-f88eccede3d3
    type: external
  - name: SAWNS Foundation
    id: 61d2bcb6-3c4d-4125-b636-bf566225e20a
    type: content
favicon: null
title: SAWNS Ltd.
purpose:
  - type: contact
    url: 'mailto:rishiram@sawnsco.com'
    label: Email Us
  - type: contact
    url: 'tel:+774803379'
    label: Call +774803379
content: []
url: 'https://sawnsco.com'
