name: Sawnsco
favicon: null
layout_spectrum: 0.02076
typography_spectrum: 1
title: SAWNS Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76571740-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#027fb3'
    - '#959595'
    - '#666666'
    - '#043950'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
